name: course
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.3
  flutter: 
    sdk: flutter
  circle_nav_bar: ^1.0.2  
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0  

flutter: 
  uses-material-design: true

  assets:
    - assets/